site_name: Benewah County Fairbook
site_url: https://benewahcountyfair.github.io/fairbook/

nav:
  - Home: index.md
  - Forms & Entries: forms.md
  - Schedule: schedule.md
  - Rules & Eligibility: rules.md
  - Departments:
      - Overview: departments/index.md
      - Livestock: departments/livestock.md
      - Home Arts: departments/home-arts.md
      - Youth: departments/youth.md
      - Horticulture: departments/horticulture.md
      - Baking: departments/baking.md
      - Canning: departments/canning.md
      - Photography: departments/photography.md
      - Sewing: departments/sewing.md
      - Hobbies & Crafts: departments/hobbies-and-crafts.md
      - Antiques & Collectibles: departments/antiques-and-collectibles.md
      - Fruits & Vegetables: departments/fruits-and-vegetables.md
      - Field Crops & Seeds: departments/field-crops-and-seeds.md
      - Other Departments: departments/other-departments.md
  - Maps & Parking: maps.md
  - Sponsors: sponsors.md
  - Contact: contact.md
  - Downloads:
      - Overview: downloads/README.md
      - Fairbook PDF: downloads/Fairbook-2025.pdf
      - Blank Entry Form: downloads/Blank-Entry-Form.pdf

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.footer
  language: en
extra_css:
  - overrides/styles.css

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
